version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/airbnb_db_creator.sql:/docker-entrypoint-initdb.d/airbnb_db_creator.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  pgdata:
    driver: local
networks:
  mynetwork:
    driver: bridge