# Generated by Django 5.1.1 on 2025-03-12 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airbnb_listing_id', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, null=True)),
                ('beds', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('person_capacity', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.TextField(blank=True, null=True)),
                ('room_type', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('is_bath_shared', models.BooleanField(blank=True, null=True)),
                ('baths_text', models.TextField(blank=True, null=True)),
                ('scrapped_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
