# Generated by Django 5.1.5 on 2025-08-23 23:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title_text', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superhost', models.BooleanField(default=False)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_average', models.FloatField(default=0.0)),
                ('time_as_host_years', models.IntegerField(blank=True, null=True)),
                ('time_as_host_months', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airbnb_listing_id', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, null=True)),
                ('beds', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('person_capacity', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.TextField(blank=True, null=True)),
                ('room_type', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('is_bath_shared', models.BooleanField(blank=True, null=True)),
                ('baths_text', models.TextField(blank=True, null=True)),
                ('scrapped_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listinghost')),
            ],
        ),
    ]
