# Generated by Django 5.1.5 on 2025-10-20 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='scrapped_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 20, 2, 21, 11, 162777, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
