# Generated by Django 5.1.5 on 2025-12-06 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_scrapped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='scrapped_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
